"""updated payments table

Revision ID: 06c370f790e1
Revises: b2f99f0418b1
Create Date: 2026-06-16 15:15:34.617366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c370f790e1'
down_revision: Union[str, Sequence[str], None] = 'b2f99f0418b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_session_id',
               existing_type=sa.VARCHAR(length=41),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_session_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=41),
               existing_nullable=True)
    # ### end Alembic commands ###
