"""updated payments table

Revision ID: b2f99f0418b1
Revises: eadd62ce1539
Create Date: 2026-06-16 15:12:00.194870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f99f0418b1'
down_revision: Union[str, Sequence[str], None] = 'eadd62ce1539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_session_id', sa.String(length=41), nullable=True))
    op.drop_column('payments', 'stripe_sesion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_sesion_id', sa.VARCHAR(length=41), autoincrement=False, nullable=True))
    op.drop_column('payments', 'stripe_session_id')
    # ### end Alembic commands ###
