"""create payments table

Revision ID: eadd62ce1539
Revises: b717a272e9e8
Create Date: 2026-06-16 13:35:14.520000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadd62ce1539'
down_revision: Union[str, Sequence[str], None] = 'b717a272e9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=41), nullable=False),
    sa.Column('user_id', sa.String(length=41), nullable=False),
    sa.Column('order_id', sa.String(length=41), nullable=False),
    sa.Column('stripe_sesion_id', sa.String(length=41), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='payment_status'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
