"""Updated orders table

Revision ID: a58bc6061235
Revises: 70a1c66c5f36
Create Date: 2026-06-16 13:48:33.656650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58bc6061235'
down_revision: Union[str, Sequence[str], None] = '70a1c66c5f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the columns as nullable=True first
    op.add_column('orders', sa.Column('price_per_litre', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=True))

    # 2. Backfill existing records with a default value so they aren't NULL
    op.execute("UPDATE orders SET price_per_litre = 0.0 WHERE price_per_litre IS NULL")
    op.execute("UPDATE orders SET total_amount = 0.0 WHERE total_amount IS NULL")

    # 3. Now alter the columns to enforce NOT NULL safely
    op.alter_column('orders', 'price_per_litre', nullable=False)
    op.alter_column('orders', 'total_amount', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'price_per_litre')
    # ### end Alembic commands ###
