"""create orders table

Revision ID: f9f04a7d29c2
Revises: 
Create Date: 2026-06-13 17:35:55.396906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f04a7d29c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=41), nullable=False),
    sa.Column('user_id', sa.String(length=41), nullable=False),
    sa.Column('quantity_litres', sa.Float(), nullable=False),
    sa.Column('delivary_date', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'PAID', 'PROCESSING', 'DELIVERED', name='order_status'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
